export const storiesData = [
  {
    id: 1,
    name: 'Harsh Beniwal',
    username: 'harsh099',
    profile: require('../../assets/man1.jpg'),
    profileAlt: 'Profile-pic',
    time: 8,
    image: require('../../assets/man1.jpg'),
    story: [
      {image: require('../../assets/girl1.jpg')},
      {image: require('../../assets/man2.jpg')},
      {image: require('../../assets/man3.jpg')},
      {image: require('../../assets/man1.jpg')},
    ],
    alt: 'Story-image-1',
  },
  {
    id: 2,
    name: 'Jasmin',
    username: 'Jasmin125578999789',
    profile: require('../../assets/girl1.jpg'),
    profileAlt: 'Profile-pic',
    time: 3,
    image: require('../../assets/girl1.jpg'),
    story: [
      {image: require('../../assets/girl2.jpg')},
      {image: require('../../assets/man3.jpg')},

    ],
    alt: 'Story-image-2',
  },
  {
    id: 3,
    name: 'Panda',
    username: 'panda11',
    profile: require('../../assets/man3.jpg'),
    profileAlt: 'Profile-pic',
    time: 9,
    image: require('../../assets/man3.jpg'),
    story: [
      {image: require('../../assets/man3.jpg')},
    ],
    alt: 'Story-image-3',
  },
  {
    id: 4,
    name: 'Sapna',
    username: 'sapnab1211',
    profile: require('../../assets/girl2.jpg'),
    profileAlt: 'Profile-pic',
    time: 10,
    image: require('../../assets/girl2.jpg'),
    story: [
      {image: require('../../assets/man1.jpg')},
      {image: require('../../assets/man2.jpg')},
      {image: require('../../assets/man3.jpg')},
    ],
    alt: 'Story-image-4',
  },
  {
    id: 5,
    name: 'Sajad',
    username: 'sajad12',
    profile: require('../../assets/man2.jpg'),
    profileAlt: 'Profile-pic',
    time: 2,
    image: require('../../assets/man2.jpg'),
    story: [
      {image: require('../../assets/girl2.jpg')},
      {image: require('../../assets/man3.jpg')},
    ],
    alt: 'Story-image-5',
  },
];
