export const PostData = [
  {
    id: 1,
    name: 'Harsh Beniwal',
    username: 'harsh099',
    profile: require('../../assets/man1.jpg'),
    profileAlt: 'Profile-pic',
    time: '04:00 PM',
    date: '08 January 2024',
    image: require('../../assets/man1.jpg'),
    postImages: [
      require('../../assets/man1.jpg'),
    ],
    caption: 'hi....',
    like: 25,
  },

  {
    id: 2,
    name: 'Jasmin',
    username: 'Jasmin125578999789',
    profile: require('../../assets/girl1.jpg'),
    alt: 'Profile-image',
    time: '07:30 AM',
    date: '12 December 2023',
    image: require('../../assets/girl1.jpg'),
    postImages: [require('../../assets/girl1.jpg')],
    caption: 'wandering',
    like: 288,
  },
  {
    id: 3,
    name: 'Panda',
    username: 'panda11',
    profile: require('../../assets/man3.jpg'),
    alt: 'Profile-image',
    time: '09:00 AM',
    date: '23 June 2023',
    image: require('../../assets/man3.jpg'),
    postImages: [require('../../assets/man3.jpg')],
    caption: 'panda',
    like: 48,
  },
  {
    id: 4,
    name: 'Sapna',
    username: 'sapnab1211',
    profile: require('../../assets/girl2.jpg'),
    alt: 'Profile-image',
    time: '05:00 AM',
    date: '12 May 2023',
    image: require('../../assets/girl2.jpg'),
    postImages: [
      require('../../assets/girl2.jpg'),
      require('../../assets/girl1.jpg'),
      require('../../assets/man1.jpg'),
    ],
    caption: 'Nature',
    like: 97,
  },
  {
    id: 5,
    name: 'Sajad',
    username: 'sajad12',
    profile: require('../../assets/man2.jpg'),
    alt: 'Profile-image',
    time: '07:00 AM',
    date: '28 January 2024',
    image: require('../../assets/man2.jpg'),
    postImages: [
      require('../../assets/man2.jpg'),
      require('../../assets/girl2.jpg'),
      require('../../assets/girl1.jpg'),
    ],
    caption: 'loading...',
    like: 188,
  },
];
