export const UserData = [
    {
      id: 1,
      name: 'Harsh Beniwal',
      username: 'harsh099',
      profile: require('../../assets/man1.jpg'),
      profileAlt:'Profile-pic',
      bio: 'Standup Comedian',
      address: 'Bangalore , Karnataka',
      followers: '1.5M',
      following: '112',
      images: [
        require('../../assets/man1.jpg'),
        require('../../assets/man1.jpg'),
        require('../../assets/man1.jpg'),
        require('../../assets/man1.jpg'),
        require('../../assets/man1.jpg'),
    ],
      
    },
  
    {
      id: 2,
      name: 'Jasmin',
      username: 'Jasmin125578999789',
      profile: require('../../assets/girl1.jpg'),
      alt: 'Profile-image',
      bio: 'Kuch b...',
      address: 'Bangalore , Karnataka',
      followers: '455k',
      following: '345',
      images: [
        require('../../assets/girl1.jpg'),
        require('../../assets/girl1.jpg'),
        require('../../assets/girl1.jpg'),
        require('../../assets/girl1.jpg'),
        require('../../assets/girl1.jpg'),
    ],
      
    },
    {
      id: 3,
      name: 'Panda',
      username: 'panda11',
      profile: require('../../assets/man3.jpg'),
      alt: 'Profile-image',
      bio: 'kanfu Panda',
      address: 'Mysore, Karnataka',
      followers: '55k',
      following: '34',
      images: [
        require('../../assets/man3.jpg'),
        require('../../assets/man3.jpg'),
        require('../../assets/man3.jpg'),
        require('../../assets/man3.jpg'),
    ],
      
    },
    {
      id: 4,
      name: 'Sapna',
      username: 'sapnab1211',
      profile: require('../../assets/girl2.jpg'),
      alt: 'Profile-image',
      bio: 'papa ki pari',
      address: 'Bangalore , Karnataka',
      followers: '5',
      following: '24',
      images: [
        require('../../assets/girl2.jpg'),
        require('../../assets/girl2.jpg'),
        require('../../assets/girl2.jpg'),
    ],
     
    },
    {
      id: 5,
      name: 'Sajad',
      username: 'sajad12',
      profile: require('../../assets/man2.jpg'),
      alt: 'Profile-image',
      bio: 'Wanderer',
      address: 'Gulmarg, Kashmir',
      followers: '45M',
      following: '2',
      images: [
        require('../../assets/man1.jpg'),
        require('../../assets/man1.jpg'),
        require('../../assets/man1.jpg'),
        require('../../assets/man1.jpg'),
        require('../../assets/man2.jpg'),
        require('../../assets/man2.jpg'),
        require('../../assets/man2.jpg'),
        require('../../assets/man2.jpg'),
        require('../../assets/man2.jpg'),
        require('../../assets/man2.jpg'),
        require('../../assets/man2.jpg'),
        require('../../assets/man2.jpg'),
        require('../../assets/man2.jpg'),
        require('../../assets/man2.jpg'),
        require('../../assets/man2.jpg'),
    ],
    },
  ];